# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170307_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
