# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170307_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
