# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170307_1934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
    ]
